### ISSUE TITLE
ValueError: length of the sample (35) must correspond to the stream's channel count (36).

### ISSUE THREAD

**Issue by Nicobruno92** [hynchl/lsl-gp3#1]
I am trying to run the run.bat. It starts but yield this error. 

`Received Variable :  ['CNT', 'TIME', 'TIME_TICK', 'FPOGX', 'FPOGY', 'FPOGS', 'FPOGD', 'FPOGID', 'FPOGV', 'LPOGX', 'LPOGY', 'LPOGV', 'RPOGX', 'RPOGY', 'RPOGV', 'BPOGX', 'BPOGY', 'BPOGV', 'LPCX', 'LPCY', 'LPD', 'LPS', 'LPV', 'RPCX', 'RPCY', 'RPD', 'RPS', 'RPV', 'CX', 'CY', 'CS', 'BKID', 'BKDUR', 'BKPMIN', 'USER']
Traceback (most recent call last):
  File "C:\Users\cocud\Documents\lsl-gp3\gp3-to-lsl.py", line 176, in <module>
    outlet_gaze.push_sample(samplegaze)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsl\pylsl.py", line 454, in push_sample
    raise ValueError("length of the sample (" + str(len(x)) + ") must "
ValueError: length of the sample (35) must correspond to the stream's channel count (36).`

**Comment by hynchl** [comment]
My apologies for the delay in responding.

I hope you've managed to resolve the issue by now. If not, you might want to try changing the `num_column` value to 35. You can find the specific code [here](https://github.com/hynchl/lsl-gp3/blob/c87863ca17a8a1d49b3be96789a99af82bcb7677/gp3-to-lsl.py#L94C5-L94C20).

Feel free to reach out if you still need help with this or have any other questions.
